# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
- job: PopoTestUIFramework
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
#    rp_launch: $(test.rp.launch)
#    rp_endpoint: $(test.rp.endpoint)
#    rp_project: $(test.rp.project)
#    rp_uuid: $(test.rp.uuid)
    args: '-Drp.launch=${test.rp.launch} -Drp.endpoint=${test.rp.endpoint} -Drp.project=${test.rp.project} -Drp.uuid=${test.rp.uuid} -Dsuite=$(test.suite)'
  steps:
  # Create a variable
#  - script: echo '##vso[task.setvariable variable=suite]PdfTest'
  # Print the variable
  - script: echo my variable is $(suite)
  - script: echo my variable is $(args)

  - script: echo 'Start Testing'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      goals: 'test ${args}'
