# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
- job: PopoTestUIFramework
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    rp_launch: $(rp.launch)
    rp_endpoint: $(rp.endpoint)
    rp_project: $(rp.project)
    rp_uuid: $(rp.uuid)
#    argss: '-Dsuite=$(test.suite) -Drp.launch=${rp.launch} -Drp.endpoint=${rp.endpoint} -Drp.project=${rp.project} -Drp.uuid=${rp.uuid}'
  steps:
  # Create a variable
#  - script: echo '##vso[task.setvariable variable=rp_launch]$(rp_launch)'
  - script: echo '##vso[task.setvariable variable=rp_endpoint]https://rp.epam.com'
  - script: echo '##vso[task.setvariable variable=rp.endpoint]${rp.endpoint}'
#  - script: echo '##vso[task.setvariable variable=rp_project]${rp_project}'
#  - script: echo '##vso[task.setvariable variable=rp_uuid]${rp_uuid}'
  # Print the variable
  - script: echo my variable is $(rp_launch)
  - script: echo my variable is $(rp_endpoint)
  - script: echo my variable is $(rp_project)
  - script: echo my variable is $(rp_uuid)

  - script: echo 'Start Testing'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      goals: 'test -Dsuite=$(test.suite) -Drp.launch=${rp.endpoint} -Drp.endpoint=${rp_endpoint} -Drp.project=${rp.project} -Drp.uuid=${rp_uuid}'
#      goals: 'test -Dsuite=$(test.suite) -Drp.launch=yauheni_papovich1_TEST_EXAMPLE -Drp.endpoint=https://rp.epam.com -Drp.project=yauheni_papovich1_personal -Drp.uuid=5d3844f1-48ab-40ca-86e7-c6d6f0f101f0'
