# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  the_token: $(rp.project)
  suitee: 'TestSuite'

jobs:
- job: PopoTestUIFramework
  parameters:
    name: 'name'
  steps:
  - script: echo Now I can use $(the_token)
  - script: echo Now I can use $(suitee)
  - script: echo Now I can use $({parameters.name})
  # Create a variable
  - script: echo '##vso[task.setvariable variable=myVariable]abc123'

  # Print the variable
  - script: echo my variable is $(myVariable)
  - script: echo 'Start Testing'
    env:
      SOLUTION: 'xx'
  - script: echo my variable is $(SOLUTION)

  - task: Maven@3
    inputs:
      suite: 'TestSuite'
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      goals: 'test'
