# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Set variables once
variables:
  suite: TestSuite

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Maven@3
- script: |
    echo Starting the build
    mvn clean test -Dsuite=TestSuite
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
#    goals: 'test'
