# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
- job: PopoTestUIFramework
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    the_token: $(system.rp.project)
  steps:
  - script: echo Now I can use $(the_token)
  # Create a variable
  - script: echo '##vso[task.setvariable variable=suite]TestSuite'

  # Print the variable
  - script: echo my variable is $(suite)
  - script: echo 'Start Testing'

  - task: Maven@3
    inputs:
      suite: 'TestSuite'
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      goals: 'test'
